In [5]:
!pip install numpy

In [3]:
import numpy as np

In [6]:
l = range(100000)

In [7]:
%timeit [i**2 for i in l]

6.69 ms ± 92.2 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [9]:
arr = np.array(l)
%timeit arr**2

44.6 µs ± 1.95 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [10]:
a1 = np.array([1,2,3])
a1.ndim

1

In [13]:
a1.shape #3 columns

(3,)

In [11]:
a2 = np.array([[1,2,3]])
a2.ndim

2

In [14]:
a2.shape #1 row with 3 columns

(1, 3)

In [12]:
a3 = np.array([[[1,2,3],[4,5,7]]])
a3.ndim

3

In [15]:
a3.shape #1 three dimension, 2 rows , 3 columns

(1, 2, 3)

In [16]:
a4 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
a4.ndim

3

In [17]:
a4.shape  #1 three dim, 3 rows, 3 columns

(1, 3, 3)

In [18]:
a = np.array([1,2,3,4,5,6,7,8])
print(a.ndim, a.shape)

1 (8,)


np.arange

In [19]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
list(range(1,10,0.2)) # step 0.2 not possible with python

TypeError: 'float' object cannot be interpreted as an integer

In [22]:
np.arange(1,10,0.2) # possible with numpy

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [23]:
np.array([1,'User',True, 1.3])

array(['1', 'User', 'True', '1.3'], dtype='<U32')

In [25]:
np.array([1,True, 1.3]).dtype

dtype('float64')

In [29]:
np.array([1,True,1.3])

array([1. , 1. , 1.3])

In [26]:
np.array([1,True]).dtype

dtype('int32')

In [27]:
np.array([1,True])

array([1, 1])

In [30]:
np.array([True])

array([ True])

In [31]:
np.array([True]).dtype

dtype('bool')

In [32]:
np.array(1,2,3)

TypeError: array() takes from 1 to 2 positional arguments but 3 were given

In [34]:
np.array([1,2,3],dtype='float') # convert into float, use dtype inside array

array([1., 2., 3.])

In [35]:
np.array([1,2,3]).astype('float')  # use astype outside of array

array([1., 2., 3.])

In [36]:
np.array(['aaa','bbb','ccc']).astype('float') # error

ValueError: could not convert string to float: 'aaa'

In [37]:
np.array((1,2,3),dtype='bool')

array([ True,  True,  True])

In [40]:
a = np.array(range(10,91,10))
a

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [41]:
np.array(range(10,91,10),dtype='float')

array([10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [42]:
np.array(range(10,91,10)).astype('float')

array([10., 20., 30., 40., 50., 60., 70., 80., 90.])

In [51]:
# 1
#  even numbers between 21 and 70 (70 inclusive)
np.arange(22,71,2)

array([22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54,
       56, 58, 60, 62, 64, 66, 68, 70])

In [54]:
# 1
#  odd numbers between 20 and 71 (71 inclusive)
np.arange(21,72,2)

array([21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53,
       55, 57, 59, 61, 63, 65, 67, 69, 71])

In [58]:
# 2
import numpy as np
arr = np.array([10, 20, 30, 40, 50])
arr.astype('float64')

array([10., 20., 30., 40., 50.])

In [43]:
#3
a=np.arange(10) # 0,1,2,3,4,5,6,7,8,9
print(a[2:5]) #2,3,4

[2 3 4]


In [48]:
#4
x = np.array([-5, 9 , 20 , 25, -3, 5, 16, 10,-8])
# print(x[(x >= -5) & (x <= 15)])  # -5  9  -3  5  10 
x[(x >= -5) & (x <= 15)] *= -1 # -5, 9,-3,5,10  
# print(x[(x >= -5) & (x <= 15)] *= -1)
print(x) #-9,3,-5,-10

[  5  -9  20  25   3  -5  16 -10  -8]


In [133]:
# # 7
# Sample Input: 5 10 3
# Sample Output: [5 8 11 14 17 20 23 26 29 32]
# Start of the sequence = 5, length of the sequence = 10 and step = 3.
# First point would be the start point only, second point = start + 1*step = 5 + 1*3 =8, ....... 10th point = start + (10-1)*step = 5 + 9*3 = 32
# Note: You can use either .arange() or .linspace() to solve this question.

5+np.arange(0,10)*3

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [126]:
# 7
np.arange(5,10,3)

array([5, 8])

In [122]:
# 8
arr = np.arange(5,7,0.5)
np.round(arr,decimals=2)

array([5. , 5.5, 6. , 6.5])

In [135]:
start,end,step = 2,5,0.33
arr = np.arange(start,end,step)
arr = np.round(arr,decimals=2)
arr

array([2.  , 2.33, 2.66, 2.99, 3.32, 3.65, 3.98, 4.31, 4.64, 4.97])

In [136]:
a = np.array([100, 200, 300, 400])
b = np.array([300, 200, 100, 400])
print(a == b)

[False  True False  True]


In [137]:
import numpy as np
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[-2])

6


In [140]:
arr = np.array([10, 12, 15, 17, 2, 5, 4, 6])

In [141]:
arr[[0,2,4,6]]

array([10, 15,  2,  4])

In [143]:
arr[0,2,4,6]

IndexError: too many indices for array: array is 1-dimensional, but 4 were indexed

In [144]:
arr[::2]

array([10, 15,  2,  4])

In [145]:
arr = np.array([1,2,3,4,5,6,7,8])
arr[::2] = range(10,50,10)
print(arr)

[10  2 20  4 30  6 40  8]


In [156]:
import numpy as np
def ratio(marks_arr):
    # Complete the missing code
    distinction = marks_arr[marks_arr >= 80] # Use masking to get the values
    first_div = marks_arr[(marks_arr >=60) & (marks_arr < 80)] # Use masking to get the values
    
    distinction_count = len(distinction)
    first_div_count = len(first_div)
    
    ratio = distinction_count / first_div_count
    
    return round(ratio,2)

ratio(np.array([20, 35, 68, 82, 83, 70, 90]))

1.5

In [148]:
arr = np.array([20, 35, 68, 82, 83, 70, 90])
arr[arr>=80]

array([82, 83, 90])

In [154]:
arr[(arr>=60) & (arr<80)]

array([68, 70])

In [155]:
arr[arr<60]

array([20, 35])

In [157]:
np.where(arr>=80)

(array([3, 4, 6], dtype=int64),)

In [158]:
np.where((arr>=60) & (arr<80))

(array([2, 5], dtype=int64),)