In [2]:
import numpy as np

In [172]:
data = np.loadtxt('C:\\Users\\jujju\\SharedFolder\\Coding\\Numpy\\fit.txt',dtype='str')
data
# We provide the file name along with the dtype of data that we want to load in.

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [173]:
print(data.shape, data.ndim)

(96, 6) 2


In [174]:
data[0]

array(['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
      dtype='<U10')

In [175]:
data[:5]

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active']],
      dtype='<U10')

In [176]:
# Approach 1
data[:,0] # get only 0th index -> date column alone

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [177]:
# Approach 2
data_t = data.T
data_t

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [178]:
data_t[0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [179]:
data_t.shape

(6, 96)

In [180]:
np.array([['dat1','dat2'],['stp1','stp2'],['cal1','cal2'],['act1','act2']]).shape

(4, 2)

In [181]:
a,b,c,d=np.array([['dat1','dat2'],['stp1','stp2'],['cal1','cal2'],['act1','act2']])
d

array(['act1', 'act2'], dtype='<U4')

In [203]:
a,b,c,d = np.array([6,7,8,9])  # a=6,b=7,c=8,d=9
d

9

In [182]:
date, step_count, mood, calories_burned, hours_of_sleep, activity_status = data_t

In [185]:
step_count = step_count.astype('int')
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [186]:
calories_burned = calories_burned.astype("int")
hours_of_sleep = hours_of_sleep.astype("int")

In [187]:
np.unique(mood)

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

In [188]:
mood=='Happy'

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False,  True])

In [190]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [191]:
date[mood=='Happy']

array(['18-10-2017', '29-10-2017', '31-10-2017', '01-11-2017',
       '02-11-2017', '03-11-2017', '04-11-2017', '05-11-2017',
       '06-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '19-11-2017',
       '20-11-2017', '21-11-2017', '22-11-2017', '23-11-2017',
       '24-11-2017', '25-11-2017', '26-11-2017', '27-11-2017',
       '30-11-2017', '01-12-2017', '02-12-2017', '03-12-2017',
       '04-12-2017', '05-12-2017', '06-12-2017', '14-12-2017',
       '26-12-2017', '28-12-2017', '06-01-2018', '09-01-2018'],
      dtype='<U10')

In [192]:
step_count[mood=='Happy']

array([4732,  330, 4550, 4435, 4779, 1831, 2255,  539, 5464, 4068, 4683,
       4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  269, 4275, 5999,
       4421, 6930, 5195,  546,  493,  995, 3608,  774, 1421, 4064, 2725,
       5934, 1867, 7422, 5537, 5376,  153, 2203])

In [193]:
np.mean(step_count[mood=='Happy'])

3392.725

In [195]:
np.mean(step_count[mood=='Sad'])

2103.0689655172414

# Exploratory Data Analysys (EDA)
people walk more when they are happy?
if a person is happy, does he sleep more?
If a person is happy, is he burning more calaries?

# Np.Sort

In [235]:
a = np.array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])
a

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [197]:
np.sort(a)#  output- not inplace - you have not changed the original array
#a = np.sort(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [199]:
a.sort()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [238]:
a.sort(axis=0)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [237]:
a.sort(axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [202]:
a = np.array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])
print(a)  # original
np.sort(a)
print(a) # no change in original array  # temprary output
a.sort() 
print(a)  # changing original array  # in-place or permanent output

[4 7 0 3 8 2 5 1 6 9]
[4 7 0 3 8 2 5 1 6 9]
[0 1 2 3 4 5 6 7 8 9]


In [204]:
a = np.array([[345,567,122],[54,65,21],[654,234,423]])
a

array([[345, 567, 122],
       [ 54,  65,  21],
       [654, 234, 423]])

In [205]:
np.sort(a) # sort each row separately

array([[122, 345, 567],
       [ 21,  54,  65],
       [234, 423, 654]])

In [207]:
a

array([[345, 567, 122],
       [ 54,  65,  21],
       [654, 234, 423]])

In [206]:
np.sort(a,axis=0) # 0 for column sorting

array([[ 54,  65,  21],
       [345, 234, 122],
       [654, 567, 423]])

In [209]:
a

array([[345, 567, 122],
       [ 54,  65,  21],
       [654, 234, 423]])

In [208]:
np.sort(a,axis=1)  # 1 for row sorting

array([[122, 345, 567],
       [ 21,  54,  65],
       [234, 423, 654]])

# Element-wise Multiplication
np.dot  # mostly used in industry
np.matmul
a @ b
a = [2 x 3] [ R X C]
b = [3 x 2] [ R x C]
R and C must match and C and R match
multiplication = a x b = [2 x 3] [3 x 2] # 1st and last are 2 and 2 # middle both are 3 and 3. then its possible


In [212]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [211]:
b = np.arange(6,11)
b

array([ 6,  7,  8,  9, 10])

In [213]:
a*b

array([ 6, 14, 24, 36, 50])

In [215]:
# Array * Number →→ WORKS 
# Array * Array (same shape) →→ WORKS 
# Array * Array (different shape) →→ DOES NOT WORK

np.array([1,2,3]) * np.array([1,2])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [220]:
a = np.arange(1,13).reshape(3,4)
c = np.arange(2,14).reshape(4,3)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [221]:
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [222]:
a.shape, c.shape  # [3 x 4] [4 x 3] # multiplication is possible since 3 and 3 also 4 and 4

((3, 4), (4, 3))

In [223]:
np.dot(a,c)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [224]:
np.matmul(a,c)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [225]:
a@c

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [226]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [227]:
np.matmul(a,5)  # does not support

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [228]:
a@5 # not possible

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [229]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [231]:
np.dot(a,5)  # possible

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [232]:
x = np.arange(10).reshape(5,2)
y = np.arange(2).reshape(2,1)
x,y

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),
 array([[0],
        [1]]))

In [233]:
np.dot(x,y)

array([[1],
       [3],
       [5],
       [7],
       [9]])

# **Vectorization**


In [239]:
a = np.array([1,2,3])
a+2

array([3, 4, 5])

In [240]:
a**2

array([1, 4, 9])

In [241]:
def even_odd(x):
    if x%2==0:
        return 'even'
    else:
        return 'odd'

In [243]:
a = np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [244]:
even_odd(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [247]:
a+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [246]:
a**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196])

In [245]:
for i in a:
    print(even_odd(i))

odd
even
odd
even
odd
even
odd
even
odd
even
odd
even
odd
even


In [250]:
vec_func = np.vectorize(even_odd)
vec_func(a)

array(['odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd', 'even', 'odd', 'even'], dtype='<U4')

In [252]:
# Define a function to categorize temperatures
def categorize_temperature(temp):
    if temp < 0:
        return 'Freezing'
    elif temp < 10:
        return 'Cold'
    elif temp < 20:
        return 'Cool'
    elif temp < 30:
        return 'Warm'
    else:
        return 'Hot'

# Create a numpy array of temperatures
temperatures = np.array([-5, 0, 5, 15, 25, 35])

In [253]:
vec_temp = np.vectorize(categorize_temperature)
vec_temp(temperatures)

array(['Freezing', 'Cold', 'Cold', 'Cool', 'Warm', 'Hot'], dtype='<U8')

# **Broadcasting**
<!-- transmitting the data all over -->

rule 1: If your dimensions are not matching, match them by adding 1 in starting

Ex1:   step1: (5,) (5,2) are different
       step2: (1,5) (5,2)  add 1 in the 1st
Ex2:  3D (3,7,2) (4,1) 2D  => (3,7,2) (1,4,1)
Ex3:  (7,1,8,4)  (1,7,3)   => (7,1,8,4) (1,1,7,3)
Ex4:  (3,8,4)  (4,3,2)  => cannot do anything

rule 2: If you have 1 you can change that

Ex1:
         (5,)  (3,5) 
Rule 1=> (1,5) (3,5) 
Rule 2=> (3,5) (3,5) => 1 can be changed to 3

Ex2:
        (7,3,4)  (4)
        (7,3,4)  (1,1,4)
        (7,3,4)  (7,3,4)
        
---------------------------

1 2 3  X  1 2 3
4 5 6    

[2 X 3] [1 x 3]?

1 2 3     1 2 3
4 5 6  X  1 2 3

1,2,3 extending again in next row
answer will be

2 4 6

------------------------
    1  2  3            1 2 3
    4  5  6            4 5 6
    7  8  9
    10 11 12
    
 cannot broadcast since 2 rows need to broadcast. only one row can be broadcast
 
 ------------------------
    1  2  3            1 2 3
    4  5  6            
    7  8  9
    10 11 12
    
 can be broadcast since 1 row can be repeated. only one row can be broadcast
 
 ---------------------
    1  2  3            1
    4  5  6            2
    7  8  9            3
  can be broadcast since 1 column can be repeated. only one column can be broadcast
    

In [254]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [255]:
a+2

array([[3, 4, 5],
       [6, 7, 8]])

In [256]:
b = np.array([1,2,3])
b

array([1, 2, 3])

In [257]:
a+b

array([[2, 4, 6],
       [5, 7, 9]])

In [258]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [261]:
b = np.array([[1],[2],[3]])
b

array([[1],
       [2],
       [3]])

In [262]:
a+b

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [264]:
a = np.arange(12).reshape(3,4)
b = np.array([1,2,3])
# a = (3,4)
# b = (3,)
# broadcast => (3,4) (3,1) => (3,4) (3,4) => will not work
a.shape,b.shape

((3, 4), (3,))

In [ ]:
(8,1,6,1)  (7,1,5) =>

(8,1,6,1) 
(1,7,1,5)

(8,7,6,5) # final ans


In [4]:
# 1
x = np.ones((5,5))
x[1:-1,1:-1] =0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [5]:
# 2
arr= np.array([[2,3,4,5],[1,7,3,5],[2,8,6,9],[11,23,12,19]])
arr

array([[ 2,  3,  4,  5],
       [ 1,  7,  3,  5],
       [ 2,  8,  6,  9],
       [11, 23, 12, 19]])

In [6]:
arr1 = np.array([[2,2,2,2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr,arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [7]:
arr1 = np.array([[2],[2],[2],[2]])
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [8]:
arr1 = 2
def func(x, y):
    return x * y
vec = np.vectorize(func)
vec(arr, arr1)

array([[ 4,  6,  8, 10],
       [ 2, 14,  6, 10],
       [ 4, 16, 12, 18],
       [22, 46, 24, 38]])

In [112]:
#3

mat1 = np.array([[6, 6, 4, 7, 9] , 
 [0, 2, 2, 9, 3]  ,
 [6, 0, 2, 5, 2]  ,
 [2, 4, 3, 5, 5]])  

mat2 = np.array([[8, 6, 6, 8, 3]  ,
 [2, 7, 0, 3, 1]  ,
 [3, 2, 1, 5, 2]  ,
 [7, 0, 7, 6, 8]  ,
 [1, 5, 6, 4, 5]] )

r1,r2 = 1, 3  
c1,c2 = 2, 4

# [4X5] [5X5]
np.dot(mat1,mat2)

array([[130, 131, 143, 164, 133],
       [ 76,  33,  83,  82,  93],
       [ 91,  50,  85,  96,  72],
       [ 73,  71,  80,  93,  81]])

In [113]:
mat1.shape,mat1.ndim,mat2.shape,mat2.ndim

((4, 5), 2, (5, 5), 2)

In [12]:
a = [[1,2,3],[4,5,6]]
b = [[1,2,3],[4,5,6],[7,8,9]]
# [2 X 3][3 X 3] = 1*1 + 2*4 + 3*7 = 1+8+21 = 30
np.dot(a,b)

array([[30, 36, 42],
       [66, 81, 96]])

In [114]:
import numpy as np
def specific_elements(mat1,mat2,r1,r2,c1,c2):
    '''mat1,mat2 are the two 2d numpy array.
       r1,r2 are the start and end of rows indices
       c1,c2 are the start and end of columns indices
       Output = Return a numpy array according to indices'''
    
    # STEP1 CHECK whether matrix multiplication is possible
    if mat1.shape[1] != mat2.shape[1]:
        return -1
    
    ## STEP 2 Perform matrix multiplication    
    matmul_array = np.dot(mat1,mat2)
    
    ## STEP 3 slice the array based on range value    
    result = matmul_array[r1:r2,c1:c2]    
    return result

mat1 = np.array([[6, 6, 4, 7, 9] , 
 [0, 2, 2, 9, 3]  ,
 [6, 0, 2, 5, 2]  ,
 [2, 4, 3, 5, 5]])  

mat2 = np.array([[8, 6, 6, 8, 3]  ,
 [2, 7, 0, 3, 1]  ,
 [3, 2, 1, 5, 2]  ,
 [7, 0, 7, 6, 8]  ,
 [1, 5, 6, 4, 5]] )

r1,r2 = 1, 3  
c1,c2 = 2, 4
print(specific_elements(mat1,mat2,r1,r2,c1,c2))

[[83 82]
 [85 96]]


In [88]:
birds = ['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills']
age = [5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0]

In [104]:
birds = np.array(['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills'])
age = np.array([5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0])
sorted_age = np.recarray.argsort(age)
sorted_age
birds[sorted_age]

array(['plovers', 'plovers', 'plovers', 'plovers', 'plovers', 'Cranes',
       'spoonbills', 'Cranes', 'plovers', 'spoonbills'], dtype='<U10')

In [32]:
age.sort()
age

[1.5, 2.0, 3.0, 3.5, 3.5, 4.0, 5.5, 5.5, 6.0, 6.0]

In [18]:
bird_age = list(zip(birds,age))
bird_age

[('spoonbills', 1.5),
 ('plovers', 2.0),
 ('plovers', 3.0),
 ('plovers', 3.5),
 ('plovers', 3.5),
 ('Cranes', 4.0),
 ('plovers', 5.5),
 ('plovers', 5.5),
 ('Cranes', 6.0),
 ('spoonbills', 6.0)]

In [89]:
bird_age=np.stack((birds,age),axis=1)
print(bird_age)
bird,age = bird_age.T
print(bird)
print(age)

[['spoonbills' '5.5']
 ['plovers' '6.0']
 ['plovers' '3.5']
 ['plovers' '1.5']
 ['plovers' '3.0']
 ['Cranes' '4.0']
 ['plovers' '3.5']
 ['plovers' '2.0']
 ['Cranes' '5.5']
 ['spoonbills' '6.0']]
['spoonbills' 'plovers' 'plovers' 'plovers' 'plovers' 'Cranes' 'plovers'
 'plovers' 'Cranes' 'spoonbills']
['5.5' '6.0' '3.5' '1.5' '3.0' '4.0' '3.5' '2.0' '5.5' '6.0']


In [86]:
bird_age=np.stack((birds,age),axis=0)
print(bird_age)
bird,age = bird_age
print(bird)
print(age)

[['spoonbills' 'plovers' 'plovers' 'plovers' 'plovers' 'Cranes' 'plovers'
  'plovers' 'Cranes' 'spoonbills']
 ['5.5' '6.0' '3.5' '1.5' '3.0' '4.0' '3.5' '2.0' '5.5' '6.0']]
['spoonbills' 'plovers' 'plovers' 'plovers' 'plovers' 'Cranes' 'plovers'
 'plovers' 'Cranes' 'spoonbills']
['5.5' '6.0' '3.5' '1.5' '3.0' '4.0' '3.5' '2.0' '5.5' '6.0']


In [109]:
#5

# What will the NumPy return if it compares two arrays with same number of elements? What does it return if we compare two NumPy arrays with integers?
# Vectorization is coming into play in this question.

arr1 = np.array(['Ram','Astha','Brahat','Kalyani'])
arr2 = np.array(['Shyam','Kalyan','Naveen','do'])
arr1 > arr2

# arr1 < arr2 compares each string in arr1 with the corresponding string in arr2 
# lexicographically and returns an array of Booleans indicating whether 
# each comparison is True or False. In this specific case, all comparisons result in False.

# 'Ram' > 'Shyam':
# Compare 'R' with 'S'. Since 'R' comes before 'S' in Unicode, the comparison is False.
# 'Astha' > 'Kalyan':
# Compare 'A' with 'K'. Since 'A' comes before 'K' in Unicode, the comparison is False.
# 'Brahat' > 'Naveen':
# Compare 'B' with 'N'. Since 'B' comes before 'N' in Unicode, the comparison is False.


array([False, False, False, False])

In [123]:
a = np.array([1,2,3])
b = np.array([4,5,6])
np.dot(a,b)
# [1*4 + 2*5 + 3*6] = [4+10+18]

32

In [124]:
a = np.array([[1,2,3]])
b = np.array([4,5,6])
np.dot(a,b)
# [1*4 + 2*5 + 3*6] = [4+10+18]

array([32])

In [128]:
a = np.array([[1,2,3]]) 
b = np.array([[4,5,6]])
np.dot(a,b)
# [1*4 + 2*5 + 3*6] = [4+10+18]

ValueError: shapes (1,3) and (1,3) not aligned: 3 (dim 1) != 1 (dim 0)

In [127]:
a.ndim, b.ndim

(2, 2)

In [130]:
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([1,1])
result = np.dot(arr1,arr2)
print(result)

[3 7]


In [135]:
a = np.array([[[0,0,0],[0,0,0],[0,0,0],[0,0,0]],
             [[0,0,255],[255,255,255],[0,0,0],[255,0,0]]])
b = np.array([255, 0, 255])
c = np.all(a==b, axis=1)
c

# axis=1 => row wise comparison
# [0 == 255, 0 == 0, 0 == 255], \\ all([False, True, False]), ==> False
# [0 == 255, 0 == 0, 0 == 255], \\[False, True, False],       ==> False
# [0 == 255, 0 == 0, 0 == 255], \\[False, True, False],       ==> False
# [0 == 255, 0 == 0, 0 == 255]    [False, True, False],       ==> False

# [0 == 255, 0 == 0, 255 == 255], \\    [False, True, True], ==> False
# [255 == 255, 255 == 0, 255 == 255], \\[True, False, True], ==> False
# [0 == 255, 0 == 0, 0 == 255], \\      [False, True, False], ==> False
# [255 == 255, 0 == 0, 0 == 255]        [True, True, False], ==> False


array([[False,  True, False],
       [False, False, False]])

In [ ]:
a = np.array([[[0,0,0],[0,0,0],[0,0,0],[0,0,0]],
             [[0,0,255],[255,255,255],[0,0,0],[255,0,0]]])
b = np.array([255, 0, 255])
c = np.all(a==b, axis=1)

In [149]:
birds = np.array(['spoonbills',  'plovers',  'plovers',  'plovers',  'plovers',  'Cranes',  'plovers',  'plovers',  'Cranes',  'spoonbills'])
age = np.array([5.5, 6.0, 3.5, 1.5, 3.0, 4.0, 3.5, 2.0, 5.5, 6.0])
mask = birds=='Cranes'
print(mask)
crane_ages = age[mask]
print(crane_ages)
mean_age = np.mean(crane_ages)
print(mean_age)
mean_age = round(mean_age,2)
# mean_age

[False False False False False  True False False  True False]
[4.  5.5]
4.75


In [158]:
birds = np.array(['macaw', 'owl', 'parrot', 'macaw', 'peacock', 'owl', 'macaw', 'sparrow', 'macaw', 'parrot', 'sparrow', 'parrot', 'owl', 'owl', 'macaw'])
age = np.array([8, 7, 4, 13, 11, 13, 3, 11, 14, 8, 4, 1, 3, 10, 1])

print(np.max(age))
max_age_index = np.argmax(age)
print(max_age_index)
old_bird = birds[max_age_index]
print(old_bird)
# macaw

14
8
macaw


In [159]:
arr1 = np.array([1,2,3])
arr2 = np.array([9,8,7])
np.dot(arr1, arr2)

46

In [160]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([[1], [2]])
np.dot(arr1, arr2)

array([[ 5],
       [11]])

In [161]:
arr1 = np.array([1,2,3])
k = 3
np.dot(arr1, k)

array([3, 6, 9])

In [162]:
arr1 = np.array([[1,2], [3,4]])
arr2 = np.array([1,1])
np.dot(arr1, arr2)

array([3, 7])

In [170]:
arr1 = np.array([1,2,3,6,3,2]) 
arr2 = np.array([4,2,1,3,3,2]) 
arr3 = np.zeros(len(arr1)) 
arr3

array([0., 0., 0., 0., 0., 0.])

In [166]:
for i in range(len(arr1)): 
    arr3[i] = arr1[i] * arr2[i] 
arr3

array([ 4.,  4.,  3., 18.,  9.,  4.])

In [168]:
arr3 = arr1*arr2 
arr3

array([ 4,  4,  3, 18,  9,  4])

In [169]:
for i in range(len(arr1)): 
    if(arr1[i] < 0 ): 
        arr1[i] = -1 
    else: 
        arr1[i] = 1
arr1

array([1, 1, 1, 1, 1, 1])

In [171]:
np.where(arr1 > 0, 1, -1)

array([1, 1, 1, 1, 1, 1])

In [ ]:


10 11 12 13
14 15 16 17 
18 19 20 21


In [173]:
import numpy as np
A = np.arange(9).reshape(3,3)
print(A)
print(A[:, ::-1])

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[2 1 0]
 [5 4 3]
 [8 7 6]]
