In [1]:
import numpy as np

In [21]:
# 1
#  arr has at least one value smaller than or equal to 0.6. 
# use np.any in if condition
arr = 2 * np.arange(0,2,0.5)
if np.any(arr) <= 0.6:
    print("condition satisfies")
else:
    print("condition doesn't satisfy") 

condition doesn't satisfy


In [20]:
# 2

x = np.array([[200,200,200],[300,300,300],[400,400,400]])
v = np.array([200,300,400])
print((x / v[:,None])[1][1]) 

1.0


In [13]:
p = np.array([[0], [10], [20]])
q = np.array([10, 11, 12]) 
print((p + q)[1][1]) 

21


In [11]:
# 3
# flatten() function is used to transform a multi-dimensional array into a one-dimensional array.
# In other words, it "flattens" a multi-dimensional array structure into a simple linear sequence.

a = np.array([[16, 5], [81, 6], [33, 1]])
x=np.transpose(a).reshape(2,3)
print(x.flatten())

[16 81 33  5  6  1]


In [3]:
# 4
arr = np.array([85, 18, 2, 57, 65, 44])
mask = arr>40
arr[mask]
# arr[arr>40]

array([85, 57, 65, 44])

In [22]:
# 5
a = np.array([[34, 28,55], [8, 56, 3], [77, 87, 19]])
print(a.transpose()[-2,-2])
# [[34  28  55
#  8  56   3
# 77  87  19]]
# T=>[[   34 8  77
#         28 56 87
#         55 3  19  ]]

### 56

56


In [51]:
def check_conditions(arr, k):
    '''
    INPUT: arr, k
    OUTPUT: result -> bool
    '''
    result = None
    ## STEP 1 : Create mask for the given condition
    arr = np.array(arr)
    mask = ((arr%2==0) & (arr>k))
    ## STEP 2: Use logical function on mask
    result = mask.all()
    return result

# print(check_conditions([8, 12, 16, 20],4))
print(check_conditions([1,2,3,4,5],4))

False


In [58]:
mat = np.array([[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]])
mat[::-1].T


array([[7, 4, 1],
       [8, 5, 2],
       [9, 6, 3]])

In [74]:
def extract_subarray(arr):
    '''
    INPUT: arr -> 2D array
    
    OUPUT: result -> 2D array
    '''    
    ### STEP1: Get the rows (2nd  to 4th row)    
    row_array = arr[1:4]    
#     print(row_array)

    #### STEP 2: Get the last 3 cols from the row array    
    cols_array = row_array[:,-3:]
#     print(cols_array)
    
    #### STEP3: Reverse the rows in cols array    
    result = cols_array[::-1]
    return result

arr = np.array([[ 0,  1,  2,  3],  
 [ 4,  5,  6,  7],   
 [ 8,  9, 10, 11],   
 [12, 13, 14, 15],   
 [16, 17, 18, 19]])
print(extract_subarray(arr))

[[13 14 15]
 [ 9 10 11]
 [ 5  6  7]]


In [86]:
def reverse_column(arr):
    '''
    INPUT: arr -> 2D array 
    
    OUTPUT rev_arr -> 2D array
    '''
#     a = []
#     for i in range(len(arr)):
#         a.append(arr[i][::-1])
        
    rev_arr = np.fliplr(arr)
    
    return rev_arr

arr = np.array([[0, 1, 2], 
 [3, 4, 5], 
 [6, 7, 8]])
print(reverse_column(arr))

[[2 1 0]
 [5 4 3]
 [8 7 6]]


In [94]:
l = [1,2,3,4]
m = 5
print([i+m for i in l])

[6, 7, 8, 9]


In [105]:
def merge(A, n1, B, n2):
    ans = None
    # YOUR CODE GOES HERE
    ans = A
    ans.extend(B)
#     ans = A.extend(B)
    return sorted(ans)
print(merge([-1,2,4],3,[-1,-1,1,3,5],5))

None
[-1, -1, -1, 1, 2, 3, 4, 5]


In [115]:
i = 0
def bar(x,y):
    if y==0:
        return 0
    global i
    i += 1
#     print(i,'(',x,'+bar(',x,',',y-1,'))')
    return (x+bar(x,y-1))

def foo(x,y):
    if y==0:
        return 1
    global i
    i += 1
#     print(i,'bar(',x,', foo(,',x,',',y-1,'))')
    return bar(x, foo(x,y-1))

print(foo(3,5))

243


In [121]:
s = 'hello world'
s='  good   morning'
# s = '  '
# '  test'
result = ''
for i in s.split(' '):
    if i.strip():
        result = i.strip() + ' '+ result
print(result)

morning good 


In [85]:
# creating a 3X4 matrix using nested lists
matrix_1 = [['c1', 'c2', 'c3'],
            [10, 20, 30],
            [40, 50, 60],
            [70, 80, 90]]
 
# creating an empty array to store the reversed column matrix
matrix_2 = []
 
# looping through matrix_1 and appending matrix_2
for i in range(len(matrix_1)):
    matrix_2.append(matrix_1[i][::-1])
 
print('Matrix before changing column order:\n')
for rows in matrix_1:
    print(rows)
print('\nMatrix after changing column order:\n')
for rows in matrix_2:
    print(rows)

Matrix before changing column order:

['c1', 'c2', 'c3']
[10, 20, 30]
[40, 50, 60]
[70, 80, 90]

Matrix after changing column order:

['c3', 'c2', 'c1']
[30, 20, 10]
[60, 50, 40]
[90, 80, 70]


In [79]:
a = np.array([[6, 28], [8, 56], [7, 19]])
x = np.transpose(a).reshape(1,6)
print(x)
# 6,8,7
# 28,56,19


[[ 6  8  7 28 56 19]]


In [1]:
# Working with 2D arrays (Matrices)
import numpy as np

In [3]:
a = np.array(range(16))
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [6]:
print(a.shape,a.ndim)

(16,) 1


In [8]:
# How can we convert this array to a 2-dimensional array?

# a.reshape(8,2)
a.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [9]:
a.reshape(4,5)  # 4 x 5 =20 elements are not satisfied

ValueError: cannot reshape array of size 16 into shape (4,5)

In [10]:
a.reshape(8,-1) 
# Notice that Python automatically figured out what should be the replacement of -1 argument, given that the first argument is 8.
# We can also put -1 as the first argument. As long as one argument is given, it will calculate the other one.

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11],
       [12, 13],
       [14, 15]])

In [11]:
a.reshape(-1,-1) # have to give atleast one dimension

ValueError: can only specify one unknown dimension

In [12]:
a =a.reshape(8,2)
len(a),len(a[0])

(8, 2)

In [14]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [15]:
a.shape

(3, 4)

In [16]:
a.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [17]:
a.T.shape

(4, 3)

# <img src = https://d2beiqkhq929f0.cloudfront.net/public_assets/assets/000/054/693/original/2dnp.png?1697949471 height = "600" width = "700">

In [20]:
a[1][1]  #[R,C]

5

In [21]:
a[1,1]

5

In [22]:
m1 = np.array([100,200,300,400,500])

In [23]:
m1[1,1]  #since m1 is 1D array. no Rows and columns

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [28]:
m1[[1,3]] # print indexes 1 and 3

array([200, 400])

In [30]:
m1 = np.arange(9).reshape(3,3)
m1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [31]:
m1[[0,1,2],[0,1,2]]  #elements from (0,0) (1,1) (2,2)
                    # m1[0][0], m1[1][1],m1[2][2]

array([0, 4, 8])

In [32]:
m2=np.arange(12).reshape(3,4)
m2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [33]:
m2[:2] #row 0 and 1 will be showing

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [34]:
m2[:,:2]  # gives first two columns [R:R,C:C]

array([[0, 1],
       [4, 5],
       [8, 9]])

In [35]:
m2[:,1:3] # gives 2nd and 3rd col [:] => select entire matrix 
# [1:3] => select index col 1 to 2 (3-1)

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [122]:
m2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [123]:
m2[2:3]

array([[ 8,  9, 10, 11]])

In [37]:
m2[2:3,1:2]

array([[9]])

In [126]:
m2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [128]:
m3 = m2.reshape(4,3)
m3

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [129]:
m3[1:3,1:]

array([[4, 5],
       [7, 8]])

In [132]:
# Can we extract just the element 6 from a?
m3[2,0]

6

In [135]:
m3[2][0]

6

In [136]:
m1 = np.arange(1,10).reshape(3,3)
m1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [137]:
m1[1,1] #[row,col]

5

In [138]:
m1 = np.array([100,200,300,400,500,600])
m1[2,3]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [139]:
m1

array([100, 200, 300, 400, 500, 600])

In [140]:
m1[[2,3]]

array([300, 400])

In [141]:
m1 = np.arange(9).reshape((3,3))
m1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [142]:
m1[[0,1,2],[0,1,2]] # picking m1[0][0]  m1[1][1]  m1[2][2]

array([0, 4, 8])

In [143]:
m1 = np.arange(12).reshape(3,4)
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [144]:
m1[:2]

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [145]:
m1[:,1:3]

array([[ 1,  2],
       [ 5,  6],
       [ 9, 10]])

In [146]:
m1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [147]:
m1 < 6

array([[ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False]])

In [148]:
m1[m1 < 6]

array([0, 1, 2, 3, 4, 5])

In [149]:
a = np.arange(1,11)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [150]:
np.sum(a)

55

In [151]:
np.mean(a)

5.5

In [152]:
np.min(a)

1

In [153]:
np.max(a)

10

In [154]:
a = np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [155]:
np.sum(a)

66

In [156]:
np.sum(a, axis=0)  # column sum

array([12, 15, 18, 21])

In [157]:
np.sum(a, axis=1) # row sum

array([ 6, 22, 38])

In [ ]:
Logical Operations
What if we want to check whether "any" element of array follows a specific condition?
np.any()
returns True if any of the corresponding elements in the argument arrays follow the provided condition.
Imagine you have a shopping list with items you need to buy, but you're not sure if you have enough money to buy everything.

You want to check if there's at least one item on your list that you can afford.

In this case, you can use np.any:

In [158]:
# Prices of items on your shopping list
prices = np.array([50, 45, 25, 20, 35])

# Your budget
budget = 30

# Check if there's at least one item you can afford
can_afford = np.any(prices <= budget)

if can_afford:
    print("You can buy at least one item on your list!")
else:
    print("Sorry, nothing on your list fits your budget.")

You can buy at least one item on your list!


In [159]:
# Chores status: 1 for done, 0 for not done
chores = np.array([1, 1, 1, 1, 0])

# Check if all chores are done
all_chores_done = np.all(chores == 1)

if all_chores_done:
    print("Great job! You've completed all your chores. Time to play!")
else:
    print("Finish all your chores before you can play.")


Finish all your chores before you can play.


In [160]:
a = np.array([1, 2, 3, 2])
b = np.array([2, 2, 3, 2])
c = np.array([6, 4, 4, 5])

((a <= b) & (b <= c)).all()

True

In [161]:
arr = np.array([-3,4,27,34,-2, 0, -45,-11,4, 0 ])
arr

array([ -3,   4,  27,  34,  -2,   0, -45, -11,   4,   0])

In [162]:
arr[arr>0] 

array([ 4, 27, 34,  4])

In [164]:
arr[arr>0] =1
arr

array([ -3,   1,   1,   1,  -2,   0, -45, -11,   1,   0])

In [165]:
arr[arr <0]

array([ -3,  -2, -45, -11])

In [167]:
arr[arr< 0] =-1
arr

array([-1,  1,  1,  1, -1,  0, -1, -1,  1,  0])

In [168]:
arr

array([-1,  1,  1,  1, -1,  0, -1, -1,  1,  0])

In [170]:
# Product prices
prices = np.array([45, 55, 60, 75, 40, 90])

# Apply a 10% discount to prices above $50
discounted_prices = np.where(prices > 50, prices * .9,prices)

print("Original prices:", prices)
print("Discounted prices:", discounted_prices)

Original prices: [45 55 60 75 40 90]
Discounted prices: [45.  49.5 54.  67.5 40.  81. ]


In [172]:
data = np.loadtxt('C:\\Users\\jujju\\SharedFolder\\Coding\\Numpy\\fit.txt',dtype='str')
data
# We provide the file name along with the dtype of data that we want to load in.

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active'],
       ['11-10-2017', '4545', 'Sad', '149', '6', 'Inactive'],
       ['12-10-2017', '4340', 'Sad', '140', '6', 'Inactive'],
       ['13-10-2017', '1230', 'Sad', '38', '7', 'Inactive'],
       ['14-10-2017', '61', 'Sad', '1', '5', 'Inactive'],
       ['15-10-2017', '1258', 'Sad', '40', '6', 'Inactive'],
       ['16-10-2017', '3148', 'Sad', '101', '8', 'Inactive'],
       ['17-10-2017', '4687', 'Sad', '152', '5', 'Inactive'],
       ['18-10-2017', '4732', 'Happy', '150', '6', 'Active'],
       ['19-10-2017', '3519', 'Sad', '113', '7', 'Inactive'],
       ['20-10-2017', '1580', 'Sad', '49', '5', 'Inactive'],
       ['21-10-2017', '2822', 'Sad', '86', '6', 'Inactive'],
       ['22-10

In [173]:
print(data.shape, data.ndim)

(96, 6) 2


In [174]:
data[0]

array(['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
      dtype='<U10')

In [175]:
data[:5]

array([['06-10-2017', '5464', 'Neutral', '181', '5', 'Inactive'],
       ['07-10-2017', '6041', 'Sad', '197', '8', 'Inactive'],
       ['08-10-2017', '25', 'Sad', '0', '5', 'Inactive'],
       ['09-10-2017', '5461', 'Sad', '174', '4', 'Inactive'],
       ['10-10-2017', '6915', 'Neutral', '223', '5', 'Active']],
      dtype='<U10')

In [176]:
# Approach 1
data[:,0] # get only 0th index -> date column alone

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [177]:
# Approach 2
data_t = data.T
data_t

array([['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
        '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
        '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
        '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
        '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
        '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
        '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
        '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
        '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
        '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
        '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
        '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
        '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
        '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
        '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
        '05-12-2017', '06-12-2017', '07-

In [178]:
data_t[0]

array(['06-10-2017', '07-10-2017', '08-10-2017', '09-10-2017',
       '10-10-2017', '11-10-2017', '12-10-2017', '13-10-2017',
       '14-10-2017', '15-10-2017', '16-10-2017', '17-10-2017',
       '18-10-2017', '19-10-2017', '20-10-2017', '21-10-2017',
       '22-10-2017', '23-10-2017', '24-10-2017', '25-10-2017',
       '26-10-2017', '27-10-2017', '28-10-2017', '29-10-2017',
       '30-10-2017', '31-10-2017', '01-11-2017', '02-11-2017',
       '03-11-2017', '04-11-2017', '05-11-2017', '06-11-2017',
       '07-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '18-11-2017',
       '19-11-2017', '20-11-2017', '21-11-2017', '22-11-2017',
       '23-11-2017', '24-11-2017', '25-11-2017', '26-11-2017',
       '27-11-2017', '28-11-2017', '29-11-2017', '30-11-2017',
       '01-12-2017', '02-12-2017', '03-12-2017', '04-12-2017',
       '05-12-2017', '06-12-2017', '07-12-2017', '08-12

In [179]:
data_t.shape

(6, 96)

In [180]:
np.array([['dat1','dat2'],['stp1','stp2'],['cal1','cal2'],['act1','act2']]).shape

(4, 2)

In [181]:
a,b,c,d=np.array([['dat1','dat2'],['stp1','stp2'],['cal1','cal2'],['act1','act2']])
d

array(['act1', 'act2'], dtype='<U4')

In [203]:
a,b,c,d = np.array([6,7,8,9])  # a=6,b=7,c=8,d=9
d

9

In [182]:
date, step_count, mood, calories_burned, hours_of_sleep, activity_status = data_t

In [185]:
step_count = step_count.astype('int')
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

In [186]:
calories_burned = calories_burned.astype("int")
hours_of_sleep = hours_of_sleep.astype("int")

In [187]:
np.unique(mood)

array(['Happy', 'Neutral', 'Sad'], dtype='<U10')

In [188]:
mood=='Happy'

array([False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False,  True, False,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True,  True,  True,  True,  True,  True,  True, False,
       False,  True,  True,  True,  True,  True,  True,  True, False,
       False, False, False, False, False, False,  True, False, False,
       False, False, False, False, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False, False,  True, False, False,  True])

In [190]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [191]:
date[mood=='Happy']

array(['18-10-2017', '29-10-2017', '31-10-2017', '01-11-2017',
       '02-11-2017', '03-11-2017', '04-11-2017', '05-11-2017',
       '06-11-2017', '08-11-2017', '09-11-2017', '10-11-2017',
       '11-11-2017', '12-11-2017', '13-11-2017', '14-11-2017',
       '15-11-2017', '16-11-2017', '17-11-2017', '19-11-2017',
       '20-11-2017', '21-11-2017', '22-11-2017', '23-11-2017',
       '24-11-2017', '25-11-2017', '26-11-2017', '27-11-2017',
       '30-11-2017', '01-12-2017', '02-12-2017', '03-12-2017',
       '04-12-2017', '05-12-2017', '06-12-2017', '14-12-2017',
       '26-12-2017', '28-12-2017', '06-01-2018', '09-01-2018'],
      dtype='<U10')

In [192]:
step_count[mood=='Happy']

array([4732,  330, 4550, 4435, 4779, 1831, 2255,  539, 5464, 4068, 4683,
       4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  269, 4275, 5999,
       4421, 6930, 5195,  546,  493,  995, 3608,  774, 1421, 4064, 2725,
       5934, 1867, 7422, 5537, 5376,  153, 2203])

In [193]:
np.mean(step_count[mood=='Happy'])

3392.725

In [195]:
np.mean(step_count[mood=='Sad'])

2103.0689655172414

# Exploratory Data Analysys (EDA)
people walk more when they are happy?
if a person is happy, does he sleep more?
If a person is happy, is he burning more calaries?

# Np.Sort

In [235]:
a = np.array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])
a

array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])

In [197]:
np.sort(a)#  output- not inplace - you have not changed the original array
#a = np.sort(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [199]:
a.sort()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [238]:
a.sort(axis=0)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [237]:
a.sort(axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [202]:
a = np.array([4, 7, 0, 3, 8, 2, 5, 1, 6, 9])
print(a)  # original
np.sort(a)
print(a) # no change in original array  # temprary output
a.sort() 
print(a)  # changing original array  # in-place or permanent output

[4 7 0 3 8 2 5 1 6 9]
[4 7 0 3 8 2 5 1 6 9]
[0 1 2 3 4 5 6 7 8 9]


In [204]:
a = np.array([[345,567,122],[54,65,21],[654,234,423]])
a

array([[345, 567, 122],
       [ 54,  65,  21],
       [654, 234, 423]])

In [205]:
np.sort(a) # sort each row separately

array([[122, 345, 567],
       [ 21,  54,  65],
       [234, 423, 654]])

In [207]:
a

array([[345, 567, 122],
       [ 54,  65,  21],
       [654, 234, 423]])

In [206]:
np.sort(a,axis=0) # 0 for column sorting

array([[ 54,  65,  21],
       [345, 234, 122],
       [654, 567, 423]])

In [209]:
a

array([[345, 567, 122],
       [ 54,  65,  21],
       [654, 234, 423]])

In [208]:
np.sort(a,axis=1)  # 1 for row sorting

array([[122, 345, 567],
       [ 21,  54,  65],
       [234, 423, 654]])

# Element-wise Multiplication
np.dot  # mostly used in industry
np.matmul
a @ b
a = [2 x 3] [ R X C]
b = [3 x 2] [ R x C]
R and C must match and C and R match
multiplication = a x b = [2 x 3] [3 x 2] # 1st and last are 2 and 2 # middle both are 3 and 3. then its possible


In [212]:
a = np.arange(1,6)
a

array([1, 2, 3, 4, 5])

In [211]:
b = np.arange(6,11)
b

array([ 6,  7,  8,  9, 10])

In [213]:
a*b

array([ 6, 14, 24, 36, 50])

In [215]:
# Array * Number →→ WORKS 
# Array * Array (same shape) →→ WORKS 
# Array * Array (different shape) →→ DOES NOT WORK

np.array([1,2,3]) * np.array([1,2])

ValueError: operands could not be broadcast together with shapes (3,) (2,) 

In [220]:
a = np.arange(1,13).reshape(3,4)
c = np.arange(2,14).reshape(4,3)
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [221]:
c

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13]])

In [222]:
a.shape, c.shape  # [3 x 4] [4 x 3] # multiplication is possible since 3 and 3 also 4 and 4

((3, 4), (4, 3))

In [223]:
np.dot(a,c)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [224]:
np.matmul(a,c)

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [225]:
a@c

array([[ 80,  90, 100],
       [184, 210, 236],
       [288, 330, 372]])

In [226]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [227]:
np.matmul(a,5)  # does not support

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [228]:
a@5 # not possible

ValueError: matmul: Input operand 1 does not have enough dimensions (has 0, gufunc core with signature (n?,k),(k,m?)->(n?,m?) requires 1)

In [229]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [231]:
np.dot(a,5)  # possible

array([[ 5, 10, 15, 20],
       [25, 30, 35, 40],
       [45, 50, 55, 60]])

In [232]:
x = np.arange(10).reshape(5,2)
y = np.arange(2).reshape(2,1)
x,y

(array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]),
 array([[0],
        [1]]))

In [233]:
np.dot(x,y)

array([[1],
       [3],
       [5],
       [7],
       [9]])

# **Vectorization**


In [239]:
a = np.array([1,2,3])
a+2

array([3, 4, 5])

In [240]:
a**2

array([1, 4, 9])

In [241]:
def even_odd(x):
    if x%2==0:
        return 'even'
    else:
        return 'odd'

In [243]:
a = np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [244]:
even_odd(a)

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [247]:
a+2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [246]:
a**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144, 169,
       196])

In [245]:
for i in a:
    print(even_odd(i))

odd
even
odd
even
odd
even
odd
even
odd
even
odd
even
odd
even


In [250]:
vec_func = np.vectorize(even_odd)
vec_func(a)

array(['odd', 'even', 'odd', 'even', 'odd', 'even', 'odd', 'even', 'odd',
       'even', 'odd', 'even', 'odd', 'even'], dtype='<U4')

In [252]:
# Define a function to categorize temperatures
def categorize_temperature(temp):
    if temp < 0:
        return 'Freezing'
    elif temp < 10:
        return 'Cold'
    elif temp < 20:
        return 'Cool'
    elif temp < 30:
        return 'Warm'
    else:
        return 'Hot'

# Create a numpy array of temperatures
temperatures = np.array([-5, 0, 5, 15, 25, 35])

In [253]:
vec_temp = np.vectorize(categorize_temperature)
vec_temp(temperatures)

array(['Freezing', 'Cold', 'Cold', 'Cool', 'Warm', 'Hot'], dtype='<U8')

# **Broadcasting**
<!-- transmitting the data all over -->

rule 1: If your dimensions are not matching, match them by adding 1 in starting

Ex1:   step1: (5,) (5,2) are different
       step2: (1,5) (5,2)  add 1 in the 1st
Ex2:  3D (3,7,2) (4,1) 2D  => (3,7,2) (1,4,1)
Ex3:  (7,1,8,4)  (1,7,3)   => (7,1,8,4) (1,1,7,3)
Ex4:  (3,8,4)  (4,3,2)  => cannot do anything

rule 2: If you have 1 you can change that

Ex1:
         (5,)  (3,5) 
Rule 1=> (1,5) (3,5) 
Rule 2=> (3,5) (3,5) => 1 can be changed to 3

Ex2:
        (7,3,4)  (4)
        (7,3,4)  (1,1,4)
        (7,3,4)  (7,3,4)
        
---------------------------

1 2 3  X  1 2 3
4 5 6    

[2 X 3] [1 x 3]?

1 2 3     1 2 3
4 5 6  X  1 2 3

1,2,3 extending again in next row
answer will be

2 4 6

------------------------
    1  2  3            1 2 3
    4  5  6            4 5 6
    7  8  9
    10 11 12
    
 cannot broadcast since 2 rows need to broadcast. only one row can be broadcast
 
 ------------------------
    1  2  3            1 2 3
    4  5  6            
    7  8  9
    10 11 12
    
 can be broadcast since 1 row can be repeated. only one row can be broadcast
 
 ---------------------
    1  2  3            1
    4  5  6            2
    7  8  9            3
  can be broadcast since 1 column can be repeated. only one column can be broadcast
    

In [254]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [255]:
a+2

array([[3, 4, 5],
       [6, 7, 8]])

In [256]:
b = np.array([1,2,3])
b

array([1, 2, 3])

In [257]:
a+b

array([[2, 4, 6],
       [5, 7, 9]])

In [258]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [261]:
b = np.array([[1],[2],[3]])
b

array([[1],
       [2],
       [3]])

In [262]:
a+b

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

In [264]:
a = np.arange(12).reshape(3,4)
b = np.array([1,2,3])
# a = (3,4)
# b = (3,)
# broadcast => (3,4) (3,1) => (3,4) (3,4) => will not work
a.shape,b.shape

((3, 4), (3,))

In [ ]:
(8,1,6,1)  (7,1,5) =>

(8,1,6,1) 
(1,7,1,5)

(8,7,6,5) # final ans
